### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by pushpendra9950** [Yujun-Shi/CwD#3]
I have got this error "RuntimeError: margin_ranking_loss : All input tensors should have same dimension but got sizes: input1: torch.Size([50, 1]), input2: torch.Size([50, 1]), target: torch.Size([50]) 
python3: can't open file 'occ.py': [Errno 2] No such file or directory" 
 I have tried but couldn't resolve this issue

**Comment by Yujun-Shi** [comment]
@pushpendra9950 Hi, it seems like an error due to pytorch version being too old. On my machine where I have pytorch==1.10.0, the code can run smoothly. Can you provide me with your pytorch/torchvision version, thanks

**Comment by Yujun-Shi** [comment]
@pushpendra9950 In addition, given your error message, I think you can try one simple thing:

replacing the original "loss_mr" with the following:

loss_mr = nn.MarginRankingLoss(margin=self.dist)(gt_scores.view(-1, 1), max_novel_scores.view(-1, 1), torch.ones(hard_num * self.K).to(self.device).view(-1,1))

**Comment by pushpendra9950** [comment]
@Yujun-Shi  I have replaced  the code but I have got the same type of error ''RuntimeError: margin_ranking_loss : All input tensors should have same dimension but got sizes: input1: torch.Size([6, 1]), input2: torch.Size([6, 1]), target: torch.Size([6]) ''
My PyTorch version is 1.12.0

**Comment by Yujun-Shi** [comment]
@pushpendra9950 Hi, thanks for providing the version information. I've successfully replicate your error message in Pytorch 1.12.0. Now I've updated the code in the main branch and it should be running smoothly with the Pytorch 1.12.0.

**Comment by Yujun-Shi** [comment]
@pushpendra9950 Hi, I'm closing this issue. Feel free to reopen it if you encounter any further problems. Thanks!
